import type { Dealer, ModuleDefinition, ModuleKey, ModuleUsage } from "./types";

export const MODULES: ModuleDefinition[] = [
  {
    key: "tablero",
    name: "Tablero",
    description: "Home del panel: KPIs, cuotas y acciones rápidas",
    category: "inicio",
  },
  {
    key: "prospectos",
    name: "Prospectos",
    description: "Pipeline de oportunidades comerciales",
    category: "comercial",
  },
  {
    key: "perfilador",
    name: "Perfilador express",
    description: "Motorfy · precalificación de crédito",
    category: "comercial",
  },
  {
    key: "contactos",
    name: "Contactos",
    description: "Directorio de personas del equipo comercial",
    category: "comercial",
  },
  {
    key: "leads",
    name: "Leads",
    description: "Leads entrantes (WhatsApp, web, etc.)",
    category: "comercial",
  },
  {
    key: "vehiculos",
    name: "Vehículos",
    description: "Inventario publicado, destacados, nitros y descuentos",
    category: "inventario",
  },
  {
    key: "estadisticas",
    name: "Estadísticas",
    description: "Impresiones, visitas, leads y rendimiento",
    category: "reportes",
  },
  {
    key: "usuarios",
    name: "Usuarios",
    description: "Miembros del equipo de la agencia",
    category: "administracion",
  },
  {
    key: "facturacion",
    name: "Facturación",
    description: "Historial de facturas y pagos",
    category: "administracion",
  },
  {
    key: "configuracion",
    name: "Configuración",
    description: "Datos de agencia, plan, logos y leads",
    category: "general",
  },
];

const MODULE_KEYS = MODULES.map((m) => m.key);

/** Ancla fija para evitar mismatch de hidratación server/client */
const MOCK_NOW = new Date("2026-09-21T12:00:00.000Z");

function daysAgo(days: number): string {
  const d = new Date(MOCK_NOW);
  d.setUTCDate(d.getUTCDate() - days);
  return d.toISOString();
}

function usage(
  module: ModuleKey,
  adopted: boolean,
  lastUsedDays: number | null,
  actions30d: number
): ModuleUsage {
  return {
    module,
    adopted,
    lastUsedAt: lastUsedDays === null ? null : daysAgo(lastUsedDays),
    actions30d: adopted ? actions30d : 0,
  };
}

function buildModules(
  pattern: Partial<Record<ModuleKey, [boolean, number | null, number]>>
): ModuleUsage[] {
  return MODULE_KEYS.map((key) => {
    const conf = pattern[key] ?? [false, null, 0];
    return usage(key, conf[0], conf[1], conf[2]);
  });
}

type DealerSeed = Omit<Dealer, "modules" | "marketplace"> & {
  modules: Partial<Record<ModuleKey, [boolean, number | null, number]>>;
};

function withMarketplace(dealer: DealerSeed): Dealer {
  return {
    ...dealer,
    marketplace: dealer.country === "MX" ? "Seminuevos" : "Patiotuerca",
    modules: buildModules(dealer.modules),
  };
}

const SEEDS: DealerSeed[] = [
  {
    id: "mx-001",
    name: "Ford Sanchez",
    agencyCode: "SN-MX-1042",
    country: "MX",
    city: "Toluca",
    accessType: "panel",
    tier: "enterprise",
    inventoryCount: 55,
    inventoryPublished: 55,
    inventoryUnpublished: 39,
    inventoryPending: 273,
    inventoryVerified: 4,
    impressions30d: 105854,
    visits30d: 3364,
    leads30d: 31,
    ads: { used: 55, limit: 60 },
    destacados: { used: 25, limit: 25 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 420,
    mobileSessions30d: 188,
    lastLoginAt: daysAgo(0),
    accountManager: "Ana Ruiz",
    createdAt: "2022-03-14",
    teamUsers: 4,
    modules: {
      tablero: [true, 0, 210],
      prospectos: [true, 1, 40],
      perfilador: [true, 2, 12],
      contactos: [true, 1, 25],
      leads: [true, 0, 90],
      vehiculos: [true, 0, 320],
      estadisticas: [true, 1, 55],
      usuarios: [true, 5, 8],
      facturacion: [true, 8, 6],
      configuracion: [true, 12, 4],
    },
  },
  {
    id: "mx-002",
    name: "Grupo Automotriz Norte",
    agencyCode: "SN-MX-0881",
    country: "MX",
    city: "Monterrey",
    accessType: "panel",
    tier: "enterprise",
    inventoryCount: 312,
    inventoryPublished: 278,
    inventoryUnpublished: 22,
    inventoryPending: 48,
    inventoryVerified: 40,
    impressions30d: 420100,
    visits30d: 12800,
    leads30d: 186,
    ads: { used: 278, limit: 350 },
    destacados: { used: 80, limit: 100 },
    nitros: { used: 12, limit: 30 },
    descuentos: { used: 8, limit: 20 },
    webSessions30d: 610,
    mobileSessions30d: 95,
    lastLoginAt: daysAgo(1),
    accountManager: "Ana Ruiz",
    createdAt: "2021-08-02",
    teamUsers: 12,
    modules: {
      tablero: [true, 0, 280],
      prospectos: [true, 0, 140],
      perfilador: [false, null, 0],
      contactos: [true, 2, 60],
      leads: [true, 0, 220],
      vehiculos: [true, 0, 900],
      estadisticas: [true, 1, 120],
      usuarios: [true, 4, 18],
      facturacion: [true, 10, 8],
      configuracion: [true, 20, 3],
    },
  },
  {
    id: "mx-003",
    name: "Seminuevos Express Guadalajara",
    agencyCode: "SN-MX-2210",
    country: "MX",
    city: "Guadalajara",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 74,
    inventoryPublished: 61,
    inventoryUnpublished: 8,
    inventoryPending: 15,
    inventoryVerified: 10,
    impressions30d: 68200,
    visits30d: 2100,
    leads30d: 44,
    ads: { used: 61, limit: 80 },
    destacados: { used: 18, limit: 25 },
    nitros: { used: 4, limit: 10 },
    descuentos: { used: 2, limit: 10 },
    webSessions30d: 145,
    mobileSessions30d: 210,
    lastLoginAt: daysAgo(0),
    accountManager: "Luis Ortega",
    createdAt: "2023-01-19",
    teamUsers: 3,
    modules: {
      tablero: [true, 0, 150],
      prospectos: [false, null, 0],
      perfilador: [false, null, 0],
      contactos: [true, 3, 18],
      leads: [true, 0, 110],
      vehiculos: [true, 0, 280],
      estadisticas: [false, null, 0],
      usuarios: [true, 10, 4],
      facturacion: [true, 15, 3],
      configuracion: [true, 22, 2],
    },
  },
  {
    id: "mx-004",
    name: "MotorPlaza Puebla",
    agencyCode: "SN-MX-1503",
    country: "MX",
    city: "Puebla",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 58,
    inventoryPublished: 40,
    inventoryUnpublished: 12,
    inventoryPending: 30,
    inventoryVerified: 3,
    impressions30d: 24100,
    visits30d: 780,
    leads30d: 12,
    ads: { used: 40, limit: 60 },
    destacados: { used: 8, limit: 20 },
    nitros: { used: 0, limit: 5 },
    descuentos: { used: 0, limit: 5 },
    webSessions30d: 62,
    mobileSessions30d: 18,
    lastLoginAt: daysAgo(9),
    accountManager: "Luis Ortega",
    createdAt: "2023-06-11",
    teamUsers: 2,
    modules: {
      tablero: [true, 9, 40],
      leads: [true, 12, 20],
      vehiculos: [true, 9, 90],
      usuarios: [true, 40, 2],
      facturacion: [true, 30, 1],
      configuracion: [true, 35, 1],
    },
  },
  {
    id: "mx-005",
    name: "Autolote Queretaro",
    agencyCode: "SN-MX-3099",
    country: "MX",
    city: "Querétaro",
    accessType: "crm_only",
    tier: "basic",
    inventoryCount: 95,
    inventoryPublished: 95,
    inventoryUnpublished: 0,
    inventoryPending: 0,
    inventoryVerified: 0,
    impressions30d: 51000,
    visits30d: 1600,
    leads30d: 28,
    ads: { used: 95, limit: 95 },
    destacados: { used: 0, limit: 0 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 0,
    mobileSessions30d: 0,
    lastLoginAt: null,
    accountManager: "Ana Ruiz",
    createdAt: "2024-02-01",
    teamUsers: 0,
    modules: {
      vehiculos: [true, 2, 40],
    },
  },
  {
    id: "mx-006",
    name: "Elite Cars León",
    agencyCode: "SN-MX-1777",
    country: "MX",
    city: "León",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 41,
    inventoryPublished: 38,
    inventoryUnpublished: 3,
    inventoryPending: 6,
    inventoryVerified: 8,
    impressions30d: 38900,
    visits30d: 1420,
    leads30d: 27,
    ads: { used: 38, limit: 50 },
    destacados: { used: 12, limit: 15 },
    nitros: { used: 3, limit: 8 },
    descuentos: { used: 1, limit: 5 },
    webSessions30d: 98,
    mobileSessions30d: 132,
    lastLoginAt: daysAgo(1),
    accountManager: "Luis Ortega",
    createdAt: "2023-09-05",
    teamUsers: 2,
    modules: {
      tablero: [true, 0, 90],
      prospectos: [true, 2, 35],
      perfilador: [true, 4, 8],
      contactos: [true, 3, 20],
      leads: [true, 0, 70],
      vehiculos: [true, 0, 160],
      estadisticas: [true, 5, 22],
      usuarios: [true, 14, 3],
      facturacion: [true, 18, 2],
      configuracion: [true, 20, 2],
    },
  },
  {
    id: "mx-007",
    name: "DriveMax Cancún",
    agencyCode: "SN-MX-4412",
    country: "MX",
    city: "Cancún",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 22,
    inventoryPublished: 12,
    inventoryUnpublished: 7,
    inventoryPending: 18,
    inventoryVerified: 1,
    impressions30d: 8200,
    visits30d: 240,
    leads30d: 3,
    ads: { used: 12, limit: 25 },
    destacados: { used: 2, limit: 5 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 18,
    mobileSessions30d: 4,
    lastLoginAt: daysAgo(22),
    accountManager: "María Solís",
    createdAt: "2024-05-20",
    teamUsers: 1,
    modules: {
      tablero: [true, 22, 8],
      vehiculos: [true, 22, 15],
      usuarios: [true, 45, 1],
      facturacion: [true, 28, 1],
      configuracion: [true, 30, 1],
    },
  },
  {
    id: "mx-008",
    name: "Premium Motors Mérida",
    agencyCode: "SN-MX-5120",
    country: "MX",
    city: "Mérida",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 67,
    inventoryPublished: 59,
    inventoryUnpublished: 5,
    inventoryPending: 12,
    inventoryVerified: 9,
    impressions30d: 71200,
    visits30d: 2450,
    leads30d: 38,
    ads: { used: 59, limit: 70 },
    destacados: { used: 20, limit: 25 },
    nitros: { used: 5, limit: 10 },
    descuentos: { used: 0, limit: 5 },
    webSessions30d: 170,
    mobileSessions30d: 55,
    lastLoginAt: daysAgo(2),
    accountManager: "María Solís",
    createdAt: "2022-11-30",
    teamUsers: 5,
    modules: {
      tablero: [true, 0, 120],
      prospectos: [true, 2, 50],
      contactos: [true, 4, 22],
      leads: [true, 0, 95],
      vehiculos: [true, 0, 240],
      estadisticas: [true, 3, 40],
      usuarios: [true, 8, 6],
      facturacion: [true, 12, 3],
      configuracion: [true, 16, 2],
    },
  },
  {
    id: "mx-009",
    name: "CRM Sync Tijuana",
    agencyCode: "SN-MX-6001",
    country: "MX",
    city: "Tijuana",
    accessType: "crm_only",
    tier: "pro",
    inventoryCount: 140,
    inventoryPublished: 140,
    inventoryUnpublished: 0,
    inventoryPending: 0,
    inventoryVerified: 0,
    impressions30d: 98000,
    visits30d: 3100,
    leads30d: 52,
    ads: { used: 140, limit: 140 },
    destacados: { used: 0, limit: 0 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 0,
    mobileSessions30d: 0,
    lastLoginAt: null,
    accountManager: "Ana Ruiz",
    createdAt: "2023-04-12",
    teamUsers: 0,
    modules: {
      vehiculos: [true, 1, 80],
    },
  },
  {
    id: "mx-010",
    name: "Autocentro Toluca",
    agencyCode: "SN-MX-2333",
    country: "MX",
    city: "Toluca",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 33,
    inventoryPublished: 29,
    inventoryUnpublished: 4,
    inventoryPending: 9,
    inventoryVerified: 2,
    impressions30d: 22100,
    visits30d: 690,
    leads30d: 15,
    ads: { used: 29, limit: 40 },
    destacados: { used: 6, limit: 10 },
    nitros: { used: 1, limit: 3 },
    descuentos: { used: 0, limit: 3 },
    webSessions30d: 76,
    mobileSessions30d: 88,
    lastLoginAt: daysAgo(0),
    accountManager: "Luis Ortega",
    createdAt: "2024-01-08",
    teamUsers: 2,
    modules: {
      tablero: [true, 0, 70],
      leads: [true, 0, 55],
      contactos: [true, 5, 12],
      vehiculos: [true, 0, 110],
      usuarios: [true, 12, 2],
      facturacion: [true, 20, 1],
      configuracion: [true, 18, 1],
    },
  },
  {
    id: "mx-011",
    name: "Ruedas & Co. CDMX",
    agencyCode: "SN-MX-0198",
    country: "MX",
    city: "CDMX",
    accessType: "panel",
    tier: "enterprise",
    inventoryCount: 205,
    inventoryPublished: 190,
    inventoryUnpublished: 10,
    inventoryPending: 25,
    inventoryVerified: 35,
    impressions30d: 512000,
    visits30d: 16400,
    leads30d: 240,
    ads: { used: 190, limit: 220 },
    destacados: { used: 60, limit: 80 },
    nitros: { used: 20, limit: 40 },
    descuentos: { used: 15, limit: 30 },
    webSessions30d: 505,
    mobileSessions30d: 240,
    lastLoginAt: daysAgo(0),
    accountManager: "Ana Ruiz",
    createdAt: "2020-12-01",
    teamUsers: 15,
    modules: {
      tablero: [true, 0, 300],
      prospectos: [true, 0, 180],
      perfilador: [true, 1, 45],
      contactos: [true, 0, 90],
      leads: [true, 0, 260],
      vehiculos: [true, 0, 780],
      estadisticas: [true, 0, 160],
      usuarios: [true, 2, 22],
      facturacion: [true, 5, 10],
      configuracion: [true, 8, 5],
    },
  },
  {
    id: "mx-012",
    name: "Lotemóvil Aguascalientes",
    agencyCode: "SN-MX-7788",
    country: "MX",
    city: "Aguascalientes",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 19,
    inventoryPublished: 8,
    inventoryUnpublished: 6,
    inventoryPending: 20,
    inventoryVerified: 0,
    impressions30d: 3100,
    visits30d: 90,
    leads30d: 1,
    ads: { used: 8, limit: 20 },
    destacados: { used: 0, limit: 5 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 12,
    mobileSessions30d: 0,
    lastLoginAt: daysAgo(35),
    accountManager: "María Solís",
    createdAt: "2024-07-15",
    teamUsers: 1,
    modules: {
      tablero: [true, 35, 4],
      vehiculos: [true, 35, 8],
      usuarios: [true, 50, 1],
      facturacion: [true, 40, 1],
    },
  },
  {
    id: "ec-001",
    name: "Patio Tuerca Quito Premium",
    agencyCode: "PT-EC-0101",
    country: "EC",
    city: "Quito",
    accessType: "panel",
    tier: "enterprise",
    inventoryCount: 128,
    inventoryPublished: 115,
    inventoryUnpublished: 8,
    inventoryPending: 18,
    inventoryVerified: 22,
    impressions30d: 188000,
    visits30d: 6200,
    leads30d: 96,
    ads: { used: 115, limit: 140 },
    destacados: { used: 35, limit: 50 },
    nitros: { used: 8, limit: 20 },
    descuentos: { used: 4, limit: 15 },
    webSessions30d: 290,
    mobileSessions30d: 175,
    lastLoginAt: daysAgo(0),
    accountManager: "Carla Méndez",
    createdAt: "2021-05-18",
    teamUsers: 8,
    modules: {
      tablero: [true, 0, 200],
      prospectos: [true, 0, 110],
      perfilador: [true, 3, 20],
      contactos: [true, 1, 45],
      leads: [true, 0, 150],
      vehiculos: [true, 0, 480],
      estadisticas: [true, 1, 80],
      usuarios: [true, 6, 10],
      facturacion: [true, 9, 5],
      configuracion: [true, 14, 3],
    },
  },
  {
    id: "ec-002",
    name: "Motos Guayaquil Center",
    agencyCode: "PT-EC-0220",
    country: "EC",
    city: "Guayaquil",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 96,
    inventoryPublished: 88,
    inventoryUnpublished: 5,
    inventoryPending: 10,
    inventoryVerified: 14,
    impressions30d: 112000,
    visits30d: 4100,
    leads30d: 72,
    ads: { used: 88, limit: 100 },
    destacados: { used: 22, limit: 30 },
    nitros: { used: 6, limit: 12 },
    descuentos: { used: 2, limit: 8 },
    webSessions30d: 155,
    mobileSessions30d: 260,
    lastLoginAt: daysAgo(0),
    accountManager: "Carla Méndez",
    createdAt: "2022-09-09",
    teamUsers: 4,
    modules: {
      tablero: [true, 0, 140],
      prospectos: [false, null, 0],
      perfilador: [false, null, 0],
      contactos: [true, 2, 30],
      leads: [true, 0, 130],
      vehiculos: [true, 0, 340],
      estadisticas: [false, null, 0],
      usuarios: [true, 8, 5],
      facturacion: [true, 12, 3],
      configuracion: [true, 15, 2],
    },
  },
  {
    id: "ec-003",
    name: "Andes Motors Cuenca",
    agencyCode: "PT-EC-0334",
    country: "EC",
    city: "Cuenca",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 45,
    inventoryPublished: 41,
    inventoryUnpublished: 3,
    inventoryPending: 7,
    inventoryVerified: 5,
    impressions30d: 40200,
    visits30d: 1350,
    leads30d: 22,
    ads: { used: 41, limit: 50 },
    destacados: { used: 10, limit: 15 },
    nitros: { used: 2, limit: 5 },
    descuentos: { used: 0, limit: 5 },
    webSessions30d: 88,
    mobileSessions30d: 42,
    lastLoginAt: daysAgo(3),
    accountManager: "Diego Palma",
    createdAt: "2023-03-22",
    teamUsers: 3,
    modules: {
      tablero: [true, 1, 70],
      prospectos: [true, 4, 25],
      contactos: [true, 5, 15],
      leads: [true, 1, 45],
      vehiculos: [true, 1, 140],
      estadisticas: [true, 6, 18],
      usuarios: [true, 12, 3],
      facturacion: [true, 18, 2],
      configuracion: [true, 20, 1],
    },
  },
  {
    id: "ec-004",
    name: "Integración CRM Ambato",
    agencyCode: "PT-EC-0400",
    country: "EC",
    city: "Ambato",
    accessType: "crm_only",
    tier: "basic",
    inventoryCount: 52,
    inventoryPublished: 52,
    inventoryUnpublished: 0,
    inventoryPending: 0,
    inventoryVerified: 0,
    impressions30d: 19000,
    visits30d: 620,
    leads30d: 9,
    ads: { used: 52, limit: 52 },
    destacados: { used: 0, limit: 0 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 0,
    mobileSessions30d: 0,
    lastLoginAt: null,
    accountManager: "Diego Palma",
    createdAt: "2024-03-01",
    teamUsers: 0,
    modules: {
      vehiculos: [true, 0, 25],
    },
  },
  {
    id: "ec-005",
    name: "Ruta Sierra Machala",
    agencyCode: "PT-EC-0511",
    country: "EC",
    city: "Machala",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 28,
    inventoryPublished: 20,
    inventoryUnpublished: 5,
    inventoryPending: 8,
    inventoryVerified: 2,
    impressions30d: 15600,
    visits30d: 480,
    leads30d: 11,
    ads: { used: 20, limit: 30 },
    destacados: { used: 4, limit: 8 },
    nitros: { used: 0, limit: 2 },
    descuentos: { used: 0, limit: 2 },
    webSessions30d: 34,
    mobileSessions30d: 51,
    lastLoginAt: daysAgo(4),
    accountManager: "Diego Palma",
    createdAt: "2024-06-10",
    teamUsers: 1,
    modules: {
      tablero: [true, 2, 35],
      leads: [true, 2, 28],
      contactos: [true, 6, 8],
      vehiculos: [true, 2, 70],
      usuarios: [true, 16, 1],
      facturacion: [true, 22, 1],
      configuracion: [true, 25, 1],
    },
  },
  {
    id: "ec-006",
    name: "Pacific Bikes Manta",
    agencyCode: "PT-EC-0622",
    country: "EC",
    city: "Manta",
    accessType: "panel",
    tier: "pro",
    inventoryCount: 61,
    inventoryPublished: 55,
    inventoryUnpublished: 4,
    inventoryPending: 9,
    inventoryVerified: 7,
    impressions30d: 58400,
    visits30d: 1980,
    leads30d: 34,
    ads: { used: 55, limit: 70 },
    destacados: { used: 15, limit: 20 },
    nitros: { used: 3, limit: 8 },
    descuentos: { used: 1, limit: 5 },
    webSessions30d: 120,
    mobileSessions30d: 95,
    lastLoginAt: daysAgo(1),
    accountManager: "Carla Méndez",
    createdAt: "2023-08-17",
    teamUsers: 3,
    modules: {
      tablero: [true, 0, 100],
      prospectos: [true, 2, 40],
      perfilador: [false, null, 0],
      contactos: [true, 3, 18],
      leads: [true, 0, 80],
      vehiculos: [true, 0, 200],
      estadisticas: [true, 4, 28],
      usuarios: [true, 10, 4],
      facturacion: [true, 14, 2],
      configuracion: [true, 16, 2],
    },
  },
  {
    id: "ec-007",
    name: "Loja Motors",
    agencyCode: "PT-EC-0708",
    country: "EC",
    city: "Loja",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 16,
    inventoryPublished: 6,
    inventoryUnpublished: 4,
    inventoryPending: 14,
    inventoryVerified: 0,
    impressions30d: 2400,
    visits30d: 70,
    leads30d: 1,
    ads: { used: 6, limit: 15 },
    destacados: { used: 0, limit: 3 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 8,
    mobileSessions30d: 2,
    lastLoginAt: daysAgo(28),
    accountManager: "Diego Palma",
    createdAt: "2024-08-01",
    teamUsers: 1,
    modules: {
      tablero: [true, 28, 5],
      vehiculos: [true, 28, 10],
      usuarios: [true, 40, 1],
      facturacion: [true, 30, 1],
    },
  },
  {
    id: "ec-008",
    name: "Capital Motos Quito",
    agencyCode: "PT-EC-0815",
    country: "EC",
    city: "Quito",
    accessType: "panel",
    tier: "enterprise",
    inventoryCount: 154,
    inventoryPublished: 142,
    inventoryUnpublished: 7,
    inventoryPending: 16,
    inventoryVerified: 28,
    impressions30d: 245000,
    visits30d: 8100,
    leads30d: 118,
    ads: { used: 142, limit: 160 },
    destacados: { used: 45, limit: 55 },
    nitros: { used: 10, limit: 25 },
    descuentos: { used: 6, limit: 15 },
    webSessions30d: 340,
    mobileSessions30d: 120,
    lastLoginAt: daysAgo(0),
    accountManager: "Carla Méndez",
    createdAt: "2021-11-04",
    teamUsers: 9,
    modules: {
      tablero: [true, 0, 220],
      prospectos: [true, 0, 130],
      perfilador: [true, 2, 28],
      contactos: [true, 1, 55],
      leads: [true, 0, 170],
      vehiculos: [true, 0, 560],
      estadisticas: [true, 0, 110],
      usuarios: [true, 3, 12],
      facturacion: [true, 7, 6],
      configuracion: [true, 10, 3],
    },
  },
  {
    id: "ec-009",
    name: "Feed CRM Santo Domingo",
    agencyCode: "PT-EC-0902",
    country: "EC",
    city: "Santo Domingo",
    accessType: "crm_only",
    tier: "pro",
    inventoryCount: 78,
    inventoryPublished: 78,
    inventoryUnpublished: 0,
    inventoryPending: 0,
    inventoryVerified: 0,
    impressions30d: 36000,
    visits30d: 1100,
    leads30d: 18,
    ads: { used: 78, limit: 78 },
    destacados: { used: 0, limit: 0 },
    nitros: { used: 0, limit: 0 },
    descuentos: { used: 0, limit: 0 },
    webSessions30d: 0,
    mobileSessions30d: 0,
    lastLoginAt: null,
    accountManager: "Carla Méndez",
    createdAt: "2023-12-12",
    teamUsers: 0,
    modules: {
      vehiculos: [true, 1, 35],
    },
  },
  {
    id: "ec-010",
    name: "Valley Rides Ibarra",
    agencyCode: "PT-EC-1010",
    country: "EC",
    city: "Ibarra",
    accessType: "panel",
    tier: "basic",
    inventoryCount: 24,
    inventoryPublished: 22,
    inventoryUnpublished: 2,
    inventoryPending: 5,
    inventoryVerified: 3,
    impressions30d: 17800,
    visits30d: 560,
    leads30d: 14,
    ads: { used: 22, limit: 30 },
    destacados: { used: 5, limit: 8 },
    nitros: { used: 1, limit: 3 },
    descuentos: { used: 0, limit: 3 },
    webSessions30d: 45,
    mobileSessions30d: 68,
    lastLoginAt: daysAgo(2),
    accountManager: "Diego Palma",
    createdAt: "2024-04-18",
    teamUsers: 1,
    modules: {
      tablero: [true, 1, 40],
      leads: [true, 1, 35],
      contactos: [true, 4, 10],
      vehiculos: [true, 1, 85],
      usuarios: [true, 18, 1],
      facturacion: [true, 20, 1],
      configuracion: [true, 22, 1],
    },
  },
];

export const DEALERS: Dealer[] = SEEDS.map(withMarketplace);

export const ACTIVITY_TREND = [
  { week: "S-5", web: 1820, mobile: 980 },
  { week: "S-4", web: 1910, mobile: 1050 },
  { week: "S-3", web: 2050, mobile: 1180 },
  { week: "S-2", web: 1980, mobile: 1260 },
  { week: "S-1", web: 2140, mobile: 1340 },
  { week: "Actual", web: 2280, mobile: 1420 },
];
